### ISSUE TITLE
Feature Request: Add ImagePullSecrets to a service account

### ISSUE THREAD

**Issue by Vad1mo** [moolen/harbor-sync#20]
Besides creating secrets, the option to add [imagePullSecrets to a service account](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account) would be a pleasant addition. 

Example:

```yaml
kind: HarborSync
metadata:
  name: my-project
spec:
  type: Regex
  name: "my-project" # <--- specify harbor project
  robotAccountSuffix: "k8s-sync-robot" # <--- should be unique per kind: HarborSync
  mapping:
  - type: Translate
    namespace: "team-a" # <--- target namespace
    secret: "my-project-pull-token" # <--- target secret name
  - type: Translate
    namespace: "team-b"
    secret: "my-project-pull-token"
    serviceaccount: default # <--- add the imagePullSecret to the service account 
```
